version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: superset_postgres
    restart: always
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset_app
    restart: always
    environment:
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_SECRET_KEY=supersecretkey
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://superset:superset@postgres:5432/superset
    volumes:
      - superset_home:/app/superset_home
      - ./entrypoint.sh:/entrypoint.sh
      - ./superset_config.py:/app/pythonpath/superset_config.py
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    entrypoint: ["/bin/sh", "-c", "chmod +x /entrypoint.sh && /entrypoint.sh"]
  redis:
    image: redis:latest
    container_name: superset_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  superset_home:
  redis_data:
